import { createApp } from 'vue';
import { createRouter, createWebHistory } from 'vue-router';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faLink,
  faPlus,
  faArrowRight,
  faArrowUpRightFromSquare,
  faChartSimple,
  faBoxArchive,
  faRobot,
  faCircleCheck,
  faCirclePause,
  faEllipsis,
  faCopy,
  faPen,
  faMagnifyingGlass,
  faArrowLeft,
  faTrash,
  faGripVertical,
  faChevronUp,
  faChevronDown,
  faDownload,
  faPlay,
  faImage,
  faEye,
  faXmark,
  faNoteSticky,
  faArrowRightFromBracket,
  faShieldHalved,
  faCheck,
  faSpinner,
  faLeaf,
  faQrcode,
  faGlobe,
  faRotate,
  faKey,
  faHeading,
  faLayerGroup,
  faFilePdf,
  faFileArrowUp,
  faPaperPlane,
  faLock,
  faCaretDown,
  faPodcast,
  faCirclePlay,
  faNewspaper,
  faUser,
  faFileLines,
  faBook,
  faGraduationCap,
  faCode,
  faMicrophone,
  faCalendar,
  faEnvelope,
  faIcons,
} from '@fortawesome/free-solid-svg-icons';
import App from './App.vue';
import Dashboard from './components/Dashboard.vue';
import Editor from './components/Editor.vue';
import Analytics from './components/Analytics.vue';
import Agents from './components/Agents.vue';
import Campaigns from './components/Campaigns.vue';
import CampaignEditor from './components/CampaignEditor.vue';
import PublicPage from './components/PublicPage.vue';
import IconRules from './components/IconRules.vue';
import '@fontsource/ibm-plex-sans/latin-400.css';
import '@fontsource/ibm-plex-sans/latin-500.css';
import '@fontsource/ibm-plex-sans/latin-700.css';
import './style.css';
import { initializePwa } from './pwa';
initializePwa();
library.add(
  faLink,
  faPlus,
  faArrowRight,
  faArrowUpRightFromSquare,
  faChartSimple,
  faBoxArchive,
  faRobot,
  faCircleCheck,
  faCirclePause,
  faEllipsis,
  faCopy,
  faPen,
  faMagnifyingGlass,
  faArrowLeft,
  faTrash,
  faGripVertical,
  faChevronUp,
  faChevronDown,
  faDownload,
  faPlay,
  faImage,
  faEye,
  faXmark,
  faNoteSticky,
  faArrowRightFromBracket,
  faShieldHalved,
  faCheck,
  faSpinner,
  faLeaf,
  faQrcode,
  faGlobe,
  faRotate,
  faKey,
  faHeading,
  faLayerGroup,
  faFilePdf,
  faFileArrowUp,
  faPaperPlane,
  faLock,
  faCaretDown,
  faPodcast,
  faCirclePlay,
  faNewspaper,
  faUser,
  faFileLines,
  faBook,
  faGraduationCap,
  faCode,
  faMicrophone,
  faCalendar,
  faEnvelope,
  faIcons,
);
const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/admin', component: Dashboard },
    { path: '/admin/archived', component: Dashboard },
    { path: '/admin/sites/new', component: Editor },
    { path: '/admin/sites/:id/edit', component: Editor },
    { path: '/admin/sites/:id/analytics', component: Analytics },
    { path: '/admin/agents', component: Agents },
    { path: '/admin/icon-rules', component: IconRules },
    { path: '/admin/campaigns', component: Campaigns },
    { path: '/admin/campaigns/new', component: CampaignEditor },
    { path: '/admin/campaigns/:id', component: CampaignEditor },
    { path: '/:slug', component: PublicPage },
    { path: '/:slug/:code', component: PublicPage },
    { path: '/:pathMatch(.*)*', component: PublicPage },
  ],
});
createApp(App).component('Fa', FontAwesomeIcon).use(router).mount('#app');
